### ISSUE TITLE
advantage of cgo on darwin?

### ISSUE THREAD

**Issue by glycerine** [ScaleFT/monotime#5]
I'm probably missing something with the need for CGO on darwin. Out of genuine curiosity, is there an advantage to the CGO approach used here?

https://github.com/gavv/monotime seems to use runtime.nanotime for all platforms. The linux code here does too; https://github.com/ScaleFT/monotime/blob/master/clock_runtime_nanotime.go

I *think* `runtime.nanotime` is what the new time.Now() uses for monotonic clock source in go1.9. 

Since `runtime.nanotime` seems widely used, couldn't CGO be avoided?

**Comment by pquerna** [comment]
under go1.9, you should just use time.Now().  Under older versions, runtime.nanotme had various backends, which were less accurate.

**Comment by glycerine** [comment]
coolio. Thanks Paul. Hope you and Kristy are well.
